---
# tasks file for installdockercompose
- name: install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: yes  
  changed_when: no
